### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by lyolyalya** [KlausT/PascalCoin-CUDA#1]
well, the only question - how to use it?=)

**Comment by KlausT** [comment]
You need a Pascalcoin wallet.
Start the Proxy. You will be asked for the ip address, the port of the wallet, a short text of your choice, and the number of miners.
Then you can start the miners, one for each card.
PascalCoin-CUDA.exe d0 for the first card
PascalCoin-CUDA.exe d1 for the second card
and so on

**Comment by lyolyalya** [comment]
thanks...already found it.
any additional parameters?intensity?
and what hashrate to expect from 1070 for example?

**Comment by KlausT** [comment]
550 - 600 MH/s I think, can't remember exactly.
But right now I don't recommend mining with it.
There are rumors about not finding any blocks.

**Comment by lyolyalya** [comment]
awww...it's a pitty...whatomine tells about 40$ with my 1.8 GH=) have one day to test it=)till morning at least=)thaks for the help.

**Comment by knabeesse** [comment]
Hi and thanks for the miner.

I have an error when i launch the miner it say VCRUNTIME140.DLL not found.

**Comment by lyolyalya** [comment]
try to install vc runtime libs - http://rgho.st/8Cr7JP267

**Comment by knabeesse** [comment]
Thanks

**Comment by lyolyalya** [comment]
you welcome=)
